<?php
// Your existing PHP code
session_start();
error_reporting(0);
include('../../config/puri-conn.php');
include('include/checklogin.php');
check_login();
$title = "UChange Password";
$currentTime = date('d-m-Y h:i:s A', time());
$aid = $_SESSION['id'];

?>
<!-- Rest of your existing HTML code -->
<?php include('include/header.php');?>

<?php include('include/sidebar.php');?>

<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4">

                <div class="card-body px-0 pt-0 pb-2">
                    <div class="table-responsive p-0">
                        <p style="padding-left:10vw;color:#cb0c9f;padding-top:10px;"><?php if ($msg) {
                            echo htmlentities($msg);
                        }?></p>


                        <div style="margin:2%;">
                            <div class="form-group text-box">
                                <h4 style="text-align:center;">Coupon Code Check </h4>
                            </div>
                         
                            <h5>Duplicate Code Check </h5>

                            <?php
                            // Check for duplicate coupon codes
$sql = "SELECT coupon_code, COUNT(*) as count FROM users GROUP BY coupon_code HAVING count > 1";
$result = $con->query($sql);

// Check if there are duplicate coupon codes
if ($result->num_rows > 0) {
    // Output any duplicate coupon codes
    echo "<p style='padding-left:10vw;color:#cb0c9f;padding-top:10px;'>Duplicate Coupon Codes:</p>";
    echo "<ul style='padding-left:12vw;'>";
    while ($row = $result->fetch_assoc()) {
        echo "<li>" . htmlentities($row["coupon_code"]) . "</li>";
    }
    echo "</ul>";
} else {
    echo "<p style='padding-left:10vw;color:#cb0c9f;padding-top:10px;'>No duplicate coupon codes found.No code was used multiple times</p>";
}

                            ?>


<h5>Suspicious Code Check </h5>


<?php

// Check for coupon codes in users table that are not in coupons table
$sql = "
    SELECT DISTINCT u.coupon_code
    FROM users u
    WHERE NOT EXISTS (
        SELECT 1
        FROM coupons c
        WHERE c.coupon_code = u.coupon_code
    )
    AND u.coupon_code IS NOT NULL
";
$result = $con->query($sql);

// Check if there are coupon codes in users table not found in coupons table
if ($result->num_rows > 0) {
    // Output any coupon codes not found in coupons table
    echo "<p style='padding-left:10vw;color:#cb0c9f;padding-top:10px;'>Used Coupon Codes not generated by a Vendor:</p>";
    echo "<ul style='padding-left:12vw;'>";
    while ($row = $result->fetch_assoc()) {
        echo "<li>" . htmlentities($row["coupon_code"]) . "</li>";
    }
    echo "</ul>";
} else {
    echo "<p style='padding-left:10vw;color:#cb0c9f;padding-top:10px;'>All coupon codes used for registration where generated by vendors.</p>";
}
?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php include('include/footer.php');?>
